version: '3.7'

services:
  redis:
    image: redis:5.0.5-alpine
    networks:
      - default

  app:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - default
    depends_on:
      - redis

networks:
  default:
